kind: pipeline
name: portfolio

platform:
  os: linux
  ar—Åh: amd64

steps:
  - name: audit
    image: node:lts-alpine
    commands:
      - npm ci
      - npx npm-audit --moderate
    trigger:
      event:
        - push

  - name: build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    image: plugins/docker
    settings:
      repo: $${DOCKER_REGISTRY}/portfolio-nuxt
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      registry:
        from_secret: DOCKER_REGISTRY
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
    trigger:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
