kind: pipeline
name: portfolio

platform:
  os: linux
  ar—Åh: amd64

steps:
  - name: audit
    image: node:lts-alpine
    commands:
      - npm ci
      - npx npm-audit --moderate
    trigger:
      event:
        - push

  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t portfolio-nuxt .
      - docker tag portfolio-nuxt $${DOCKER_REGISTRY}/portfolio-nuxt
      - docker push $${DOCKER_REGISTRY}/portfolio-nuxt
    trigger:
      branch:
        - master
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
